export const constResponses = {
    'un libro o libros (utilizados para leer)': {
        'high':[
            "construir una casa para niños",
            "regla",
            "para comer",
            "ladrillo",
            "cama para gatos",
            "absorber líquido derramado",
            "enviar un mensaje secreto",
            "hacer música, se puede usar como tambor",
            "ping-pong de mesa",
            "ayudar con el equilibrio al hacer yoga",
            "Convertir un libro en un reloj colocando manecillas en la portada",
            "pañuelo",
            "Hacer un bolso con un libro viejo",
            "usar en lugar de una tabla de cortar al cortar verduras o carne",
            "hacer malabares",
        ],
        'low':[
            "posavasos",
            "combustible",
            "decoración",
            "para lanzar",
            "pisapapeles",
            "para escribir/dibujar en él",
            "relleno de espacio",
            "sujetalibros",
            "para llenar el estuche",
            "para aprender",
            "para jugar",
            "imprenta",
            "usar para elevar algo",
            "aplastar insectos",
            "hacer un collage o álbum de recortes",
        ],
    
        'gpt': [
            "Prensar flores secas con pilas pesadas para arte botánico",
            "Doblar páginas en un compartimento secreto para esconder pequeños objetos de valor",
            "Usar como soporte improvisado para laptop para mejorar la ventilación",
            "Crear un tope de puerta colocando el lomo debajo de la puerta",
            "Apilar para hacer un mini escalón y alcanzar estantes altos",
            "Pegar dos juntos como mancuernas improvisadas para ejercicios ligeros",
            "Tall ar un hueco en las páginas para hacer una caja de regalo encubierta",
            "Colocar como elevador de trípode de cámara para ajustar la altura de forma estable",
            "Usar como cortavientos para proteger una vela al aire libre",
            "Deslizar debajo de una pata de mesa inestable como calza firme",
            "Construir una escultura de reacción en cadena estilo dominó",
            "Reutilizar las cubiertas como sustitutos rígidos de portapapeles",
            "Construir una pared de privacidad para laptop en espacios abiertos",
            "Usar como almohadilla portátil para arrodillarse al jardinear",
            "Crear un reflector fotográfico improvisado con páginas blancas",
            "Hacer una prensa de tela con peso para alisar costuras",
        ],
    },

    'un tenedor o tenedores (utilizados para comer)': {
        'high':[
            "Si pones una banda elástica alrededor de los dientes de un tenedor se convierte en un mini trampolín para hormigas u otros insectos pequeños",
            "Mantener tu bebida fría congelando algunos tenedores y agregándolos al vaso",
            "tocar instrumentos musicales como el violín",
            "Si lo doblas calentándolo puedes hacer una pulsera",
            "cepillo de dientes",
            "como espejo",
            "en lugar de una mano paralizada",
            "soporte para CDs",
            "raqueta de tenis",
            "Sujetar el tenedor por los dientes y usar el mango como martillo",
            "Rizar las pestañas con los dientes de un tenedor limpio",
            "pintar con un tenedor",
            "Usar un tenedor para tocar el piano",
            "Colgar tenedores en una cuerda para hacer campanas de viento o arte móvil",
            "estaca para la tienda",
        ],
        'low':[
            "rascador de espalda",
            "recoger objetos pequeños como monedas o cuentas",
            "peinar el cabello",
            "como rastrillo",
            "sustituto de chincheta",
            "raspar la suciedad de los zapatos",
            "Usar un tenedor para abrir frascos bien cerrados",
            "utensilio para cocinar",
            "remover una bebida",
            "como marcador de páginas",
            "enrollar pasta alrededor del tenedor antes de comer",
            "sacar algo debajo del sofá",
            "como varilla de hierro",
            "hacer rayones en una ventana",
            "cocinar alimentos",
        ],
        'gpt': [
            "Usar dos tenedores como rizadores improvisados envolviendo mechones húmedos alrededor de las púas",
            "Convertir un tenedor en etiqueta para plantas grabando el nombre de la hierba en el mango y clavándolo en la tierra",
            "Pegar un tenedor a un palo como gancho para limpiar canaletas de hojas",
            "Hacer una catapulta fijando el mango y lanzando bandas elásticas desde las púas",
            "Usar un tenedor como peine para marcar líneas rectas en arcilla o masilla húmeda",
            "Crear un colgador de cuadros improvisado doblando el mango en forma de gancho",
            "Presionar las púas en mantequilla blanda para crear patrones decorativos en la superficie de pasteles",
            "Usar un tenedor para desenredar llaveros separando los aros con las púas",
            "Reutilizar un tenedor como herramienta pequeña para quitar maleza en espacios estrechos",
            "Pegar un imán a un tenedor y usarlo como soporte de bolígrafos en el refrigerador",
            "Raspar hielo de una esquina del parabrisas con el borde del mango del tenedor",
            "Crear un móvil de viento colgando varios tenedores con hilo de pescar",
            "Usar un tenedor como plantilla para pintar patrones de rayas repetidas",
            "Hacer un soporte de páginas encajando el tenedor en el lomo de un libro para mantenerlo abierto",
            "Colgar aretes pasándolos por las púas de un tenedor montado en la pared",
        ],
    },

    'una lata o latas (utilizadas para almacenar productos perecederos)': {
        'high':[
            "Usar la pestaña de una lata para hacer ropa",
            "imprenta",
            "usar como sombrero",
            "conexión eléctrica",
            "aplastarla y usarla en hockey sobre hielo",
            "como reflector en bicicleta",
            "como binoculares",
            "como piscina para hormigas",
            "como cámara estenopeica",
            "como abridor de cerveza",
            "como molde para helado",
            "usar aluminio para hacer bandejas",
            "poner latas y una tabla para hacer patineta",
            "quitar etiqueta y hacer aretes",
            "cortar y usar como salero/pimentero",
        ],
        'low':[
            "pisapapeles",
            "para almacenar objetos",
            "recolectar agua",
            "como florero",
            "para abrir",
            "portavelas",
            "dárselo a alguien que coleccione latas",
            "aplanarlas para hacer objetos",
            "como alcancía",
            "como cenicero",
            "como maceta",
            "como lavabo",
            "como soporte para pinceles",
            "como enfriador",
            "como basurero",
        ],
        'gpt': [
            "Apilar y llenar con arena para construir un conjunto modular de pesas",
            "Convertir en un móvil de jardín impulsado por el viento suspendiéndolo con cuerdas",
            "Usar como maceta para plántulas con orificios de drenaje",
            "Hacer una estufa compacta de camping con ranuras de ventilación y soporte para olla",
            "Crear un organizador de escritorio para bolígrafos y herramientas con divisores de cartón",
            "Fabricar un tambor de percusión para practicar ritmo con una membrana de globo",
            "Armar un condensador de destilador solar enfriando el vapor recolectado",
            "Construir una mini jaula de Faraday para almacenar pequeños dispositivos electrónicos",
            "Crear un comedero para pájaros con orificios laterales y una percha",
            "Usar como estación para lavar pinceles con una rejilla de alambre en el interior",
            "Construir un organizador de cables enrollándolos dentro y etiquetándolos",
            "Hacer un cortador de galletas rodante para crear patrones en la masa",
            "Crear un dispensador de hilo por gravedad con un ojal en la tapa",
            "Convertir en amplificador portátil de sonido para teléfono haciendo una ranura",
            "Usar como trampa de peces de supervivencia invirtiendo un cono de malla en la abertura",
        ],
    },
};
