export const constResponses = {
    'un libro o libros (utilizados para leer)': {
        'high':[
            "construir una casita de juegos para niños",
            "regla",
            "para comer",
            "ladrillo",
            "cama para gato",
            "absorber líquido derramado",
            "para enviar un mensaje secreto",
            "para hacer música, usándolo como tambor",
            "mesa de ping-pong",
            "ayudar con el equilibrio al hacer yoga",
            "convertir el libro en un reloj pegando manecillas en la portada",
            "pañuelo",
            "fabricar un bolso con un libro viejo",
            "usarlo en lugar de una tabla para cortar verduras o carne",
            "hacer malabares",
        ],
        'low':[
            "posavasos",
            "combustible",
            "decoración",
            "para lanzar",
            "pisapapeles",
            "para escribir o dibujar dentro",
            "rellenar un espacio",
            "sujetalibros",
            "para llenar la estantería",
            "para aprender",
            "para jugar",
            "imprenta",
            "para elevar algo",
            "para aplastar insectos",
            "para hacer un collage o álbum de recortes",
        ],

        'gpt': [
            "Prensar flores secas con pilas con peso para crear arte botánico",
            "Doblar las páginas para hacer un compartimento secreto donde esconder objetos pequeños",
            "Usarlo como soporte improvisado para una laptop y mejorar la ventilación",
            "Crear un tope de puerta encajando el lomo bajo la puerta",
            "Apilar varios para hacer un escalón y alcanzar estantes altos",
            "Pegar dos con cinta como mancuernas improvisadas para ejercicio ligero",
            "Tallar un hueco en las páginas para hacer una caja de regalo encubierta",
            "Acomodarlo como elevador para un trípode de cámara y ajustar la altura",
            "Usarlo como cortavientos para proteger una vela al aire libre",
            "Deslizarlo bajo la pata de una mesa coja como cuña estabilizadora",
            "Construir una escultura de reacción en cadena estilo dominó",
            "Reaprovechar las tapas como sustituto rígido de un portapapeles",
            "Levantar una pared de privacidad para la laptop en espacios abiertos",
            "Usarlo como rodillera portátil para trabajar en el jardín",
            "Crear un reflector de fotografía improvisado con sus páginas blancas",
            "Hacer una prensa con peso para alisar costuras de tela",
        ],
    },
    'un tenedor o tenedores (utilizados para comer)':{
        'high':[
            "Si pones una banda elástica alrededor de las puntas de un tenedor se convierte en un mini-trampolín para hormigas u otros insectos pequeños",
            "Mantén tu bebida fría congelando algunos tenedores y agregándolos al vaso",
            "tocar instrumentos musicales como el violín",
            "Si lo doblas calentándolo puedes hacer una pulsera con él",
            "un cepillo de dientes",
            "como espejo",
            "como sustituto de una mano paralizada",
            "soporte para CDs",
            "raqueta de tenis",
            "Sujeta el tenedor por las puntas y usa el mango para clavar clavos",
            "Riza tus pestañas con las puntas de un tenedor limpio",
            "pintar con un tenedor",
            "Tocar el piano con un tenedor",
            "Colgar tenedores de un hilo para hacer carillones de viento o un móvil decorativo",
            "estaca para sujetar la carpa de campaña",
        ],
        'low':[
            "rascador de espalda",
            "para recoger objetos pequeños como monedas o cuentas",
            "para peinarse",
            "como rastrillo",
            "sustituto de una chincheta",
            "raspar la suciedad de los zapatos",
            "Usar un tenedor para abrir frascos sellados",
            "utensilio para cocinar",
            "revolver una bebida",
            "como marcapáginas",
            "Enrollar pasta alrededor de un tenedor antes de comerla",
            "sacar algo de debajo del sofá",
            "como varilla de hierro",
            "para hacer rayones en una ventana",
            "para cocinar comida",
        ],
        'gpt': [
            "Usar dos tenedores como rulos improvisados enrollando mechones húmedos en las puntas",
            "Convertir un tenedor en una etiqueta para plantas grabando el nombre de la hierba en el mango y clavándolo en la tierra",
            "Pegar un tenedor con cinta a un palo como gancho para limpiar canaletas y retirar hojas",
            "Hacer una catapulta anclando el mango y disparando bandas elásticas desde las puntas",
            "Usar un tenedor como peine para marcar líneas rectas en arcilla o masilla húmeda",
            "Crear un colgador de cuadros improvisado doblando el mango en forma de gancho",
            "Presionar las puntas del tenedor en mantequilla blanda para estampar patrones decorativos sobre la masa",
            "Usar un tenedor como desenredador de llaveros, separando los aros con las puntas",
            "Reutilizar un tenedor como mini herramienta para arrancar dientes de león en espacios estrechos",
            "Pegar un imán a un tenedor y usarlo como porta-bolígrafo en la nevera",
            "Raspar el hielo de la esquina del parabrisas con el borde del mango de un tenedor",
            "Hacer un carrillón colgando varios tenedores con hilo de pescar",
            "Usar un tenedor como plantilla para pintar texturas a rayas repetitivas",
            "Hacer un atril para libros encajando el tenedor en el lomo para mantenerlo abierto",
            "Colgar aretes pasándolos por las puntas de un tenedor montado en la pared",
        ],
    },
    'una lata o latas (utilizadas para almacenar productos perecederos)':{
        'high':[
            "Usar la anilla de una lata para hacer un vestido o camiseta",
            "Imprenta",
            "usarla como sombrero",
            "conexión eléctrica",
            "aplastarla y usarla en hockey sobre hielo",
            "como reflector en una bicicleta",
            "como binoculares (con lentes adentro)",
            "como piscina para hormigas",
            "como cámara estenopeica",
            "como abridor de cervezas",
            "como molde para helado",
            "usar el aluminio para hacer bandejas",
            "Poner cuatro latas de lado, una tabla encima y patinar",
            "quitarle la etiqueta y hacer un arete",
            "cortarla por la mitad y usarla como salero y pimentero",
        ],
        'low':[
            "pisapapeles",
            "Para guardar objetos",
            "recolección de agua",
            "como florero",
            "para abrir",
            "portavela",
            "regalársela a alguien que coleccione latas",
            "aplastarla para fabricar objetos con ella",
            "como alcancía",
            "como cenicero",
            "como maceta",
            "como lavabo",
            "como porta-pinceles",
            "como hielera",
            "como bote de basura",
        ],
        'gpt': [
            "Apilarlas y rellenarlas con arena para construir un set modular de pesas libres",
            "Convertirla en un carillón de jardín movido por el viento, suspendiéndola con cuerdas",
            "Usarla como maceta semillero con orificios de drenaje",
            "Hacer una estufa de campamento compacta con ranuras de ventilación y soporte para la olla",
            "Crear un organizador de escritorio para bolígrafos y herramientas con divisiones de cartón",
            "Fabricar un tambor de percusión para practicar ritmo con una membrana de globo",
            "Armar el condensador de un destilador solar enfriando el vapor recolectado",
            "Construir una mini jaula de Faraday para guardar pequeños componentes electrónicos",
            "Hacer un comedero para pájaros con aberturas laterales y una varilla como percha",
            "Usarla como estación para enjuagar pinceles con una rejilla de alambre adentro",
            "Construir un organizador de cables enrollándolos dentro y etiquetándolos",
            "Hacer un cortador de galletas tipo rodillo para estampar patrones en la masa",
            "Crear un dispensador de hilo por gravedad con un ojal en la tapa",
            "Convertirla en un amplificador portátil para el altavoz del teléfono encajándolo dentro",
            "Usarla como trampa de supervivencia para peces invirtiendo un cono de malla en la abertura",
        ]
    },
}
