export const constResponses = {
    'un libro o libros (utilizados para leer)': {
        'high':[
            "construir una casa para niños",
            "regla",
            "para comer",
            "ladrillo",
            "cama para gatos",
            "absorber líquido derramado",
            "enviar un mensaje secreto",
            "hacer música, se puede usar como tambor",
            "ping-pong de mesa",
            "ayudar con el equilibrio al hacer yoga",
            "Convertir un libro en un reloj colocando manecillas en la portada",
            "pañuelo",
            "Hacer un bolso con un libro viejo",
            "usar en lugar de una tabla de cortar al cortar verduras o carne",
            "hacer malabares",
        ],
        'low':[
            "posavasos",
            "combustible",
            "decoración",
            "para lanzar",
            "pisapapeles",
            "para escribir/dibujar en él",
            "relleno de espacio",
            "sujetalibros",
            "para llenar el estuche",
            "para aprender",
            "para jugar",
            "imprenta",
            "usar para elevar algo",
            "aplastar insectos",
            "hacer un collage o álbum de recortes",
        ],
    
        'gpt': [
            "Forrar e impermeabilizar un libro de tapa dura vaciado para usarlo como maceta para suculentas.",
            "Montar un libro de tapa dura en la pared y atornillar pequeños ganchos en el lomo para hacer un llavero.",
            "Doblar páginas en macetas de origami para iniciar plántulas que se puedan plantar completas.",
            "Unir varios libros con bisagras de tela en zigzag para crear un biombo plegable.",
            "Tallarlo con canales inclinados para crear un rompecabezas de recorrido de canicas portátil.",
            "Instalar un mecanismo de reloj en un libro de tapa dura para convertirlo en reloj de pared.",
            "Usar los bordes de las páginas como mini tabla de lavar para lavar calcetines a mano en viajes.",
            "Atar dos libros pesados alrededor de un objeto pegado para usarlos como prensa portátil.",
            "Ocultar una base de carga inalámbrica dentro de un libro hueco para hacer un cargador disfrazado.",
            "Atornillar libros viejos en una pila en espiral para formar la base de una mesa auxiliar.",
            "Convertir cubiertas de libros en papel de regalo duradero o forros decorativos de sobres.",
            "Colocar un libro abierto con papel aluminio detrás de una lámpara LED como reflector de luz plegable.",
            "Enrollar hilos de urdimbre alrededor de un libro para usarlo como telar portátil simple.",
            "Agregar correas elásticas a un libro para convertirlo en escritorio portátil con soportes.",
            "Cortar ranuras en un libro grueso para crear un organizador de escritorio para notas y correo.",
        ]
    },

    'un tenedor o tenedores (utilizados para comer)': {
        'high':[
            "Si pones una banda elástica alrededor de los dientes de un tenedor se convierte en un mini trampolín para hormigas u otros insectos pequeños",
            "Mantener tu bebida fría congelando algunos tenedores y agregándolos al vaso",
            "tocar instrumentos musicales como el violín",
            "Si lo doblas calentándolo puedes hacer una pulsera",
            "cepillo de dientes",
            "como espejo",
            "en lugar de una mano paralizada",
            "soporte para CDs",
            "raqueta de tenis",
            "Sujetar el tenedor por los dientes y usar el mango como martillo",
            "Rizar las pestañas con los dientes de un tenedor limpio",
            "pintar con un tenedor",
            "Usar un tenedor para tocar el piano",
            "Colgar tenedores en una cuerda para hacer campanas de viento o arte móvil",
            "estaca para la tienda",
        ],
        'low':[
            "rascador de espalda",
            "recoger objetos pequeños como monedas o cuentas",
            "peinar el cabello",
            "como rastrillo",
            "sustituto de chincheta",
            "raspar la suciedad de los zapatos",
            "Usar un tenedor para abrir frascos bien cerrados",
            "utensilio para cocinar",
            "remover una bebida",
            "como marcador de páginas",
            "enrollar pasta alrededor del tenedor antes de comer",
            "sacar algo debajo del sofá",
            "como varilla de hierro",
            "hacer rayones en una ventana",
            "cocinar alimentos",
        ],
        'gpt': [
            "Dar forma al mango y dientes para crear un soporte minimalista para teléfono.",
            "Usarlo como pequeño rastrillo para un jardín zen de escritorio.",
            "Presionarlo en la tierra para marcar filas de siembra rectas.",
            "Colgar varios en una cuerda para hacer un móvil sonoro.",
            "Doblar los dientes hacia afuera para sostener fotos o tarjetas.",
            "Colocarlo en una puerta como tope temporal.",
            "Pasarlo por pintura para crear texturas uniformes.",
            "Clavarlo en una maceta para etiquetar plantas.",
            "Convertirlo en tirador de cajón atornillándolo.",
            "Usarlo como raspador de hielo improvisado.",
            "Enrollar auriculares para evitar enredos.",
            "Sujetarlo a piezas pequeñas como disipador de calor al soldar.",
            "Marcar arcilla con los dientes para cerámica.",
            "Montarlo para exhibir aretes.",
            "Sujetarlo a manteles como peso en días ventosos.",
        ]
    },

    'una lata o latas (utilizadas para almacenar productos perecederos)': {
        'high':[
            "Usar la pestaña de una lata para hacer ropa",
            "imprenta",
            "usar como sombrero",
            "conexión eléctrica",
            "aplastarla y usarla en hockey sobre hielo",
            "como reflector en bicicleta",
            "como binoculares",
            "como piscina para hormigas",
            "como cámara estenopeica",
            "como abridor de cerveza",
            "como molde para helado",
            "usar aluminio para hacer bandejas",
            "poner latas y una tabla para hacer patineta",
            "quitar etiqueta y hacer aretes",
            "cortar y usar como salero/pimentero",
        ],
        'low':[
            "pisapapeles",
            "para almacenar objetos",
            "recolectar agua",
            "como florero",
            "para abrir",
            "portavelas",
            "dárselo a alguien que coleccione latas",
            "aplanarlas para hacer objetos",
            "como alcancía",
            "como cenicero",
            "como maceta",
            "como lavabo",
            "como soporte para pinceles",
            "como enfriador",
            "como basurero",
        ],
        'gpt': [
            "Anidar dos latas para crear una estufa compacta.",
            "Forrar una lata para hacer una jaula de Faraday.",
            "Usarla como protector de árboles contra roedores.",
            "Aplanarla para nivelar superficies.",
            "Cortarla en tiras para etiquetas resistentes.",
            "Usarla como molde para cortar juntas.",
            "Perforarla para usarla como protector contra viento.",
            "Agregar orificios para hacer un encendedor de carbón.",
            "Usarla para separar semillas.",
            "Formar un escudo reflectante para plantas.",
            "Sellarla parcialmente como instrumento de percusión.",
            "Montarla como pasacables protector.",
            "Perforarla para riego por goteo.",
            "Convertirla en separador ciclónico.",
            "Usar el borde para trazar círculos.",
        ]
    },
};
